#!/bin/bash

$ART_PKG_NAME = piranhagui_1.3.3prerelease-1_arm64
mkdir $ART_PKG_NAME
mkdir -p $ART_PKG_NAME/usr/local/ARTIFICE
mkdir -p $ART_PKG_NAME/usr/share/applications
cp ./linux_dist_files/piranhaGUI.desktop $ART_PKG_NAME/usr/share/applications
source build_artifice
cp ./dist $ART_PKG_NAME/usr/local/ARTIFICE
mkdir -p $ART_PKG_NAME/DEBIAN
cp ./linux_dist_files/control $ART_PKG_NAME/DEBIAN/
dpkg-deb --build --root-owner-group $ART_PKG_NAME