#!/bin/bash

mkdir /usr/local/ARTIFICE
docker run -d --name="compile_art" --volume=/Users/corey/ARTIFICE/deb_test:/data/artifice/artifice/linux_build/pkg_file artifice_linux_compiler #/usr/local/ARTIFICE/deb_test:/data/artifice/artifice/linux_build/dist artifice_linux_compiler #~/ARTIFICE/ubuntu_release:/data/artifice/artifice/linux_build/dist compile_artifice
docker wait compile_art
docker rm compile_art
#sudo cp ./linux_dist_files/piranhaGUI/piranhaGUI.desktop /usr/share/applications
