#!/bin/bash

$ART_PKG_NAME = piranhagui_1.3.5
mkdir $ART_PKG_NAME
mkdir -p $ART_PKG_NAME/usr/local/ARTIFICE
mkdir -p $ART_PKG_NAME/usr/share/applications
cp ./linux_dist_files/piranhaGUI.desktop $ART_PKG_NAME/usr/share/applications
source build_artifice
cp -r ./dist/ $ART_PKG_NAME/usr/local/ARTIFICE
mkdir -p $ART_PKG_NAME/DEBIAN
cp ./linux_dist_files/piranhaGUI/control $ART_PKG_NAME/DEBIAN/
mv -t $ART_PKG_NAME ./pkg_file/
cd pkg_file
dpkg-deb --build . --root-owner-group $ART_PKG_NAME